kind: Service
apiVersion: v1
metadata:
  name: csi-yoda-provisioner
  namespace: kube-system
  labels:
    app: csi-yoda-provisioner
spec:
  selector:
    app: csi-yoda-provisioner
  ports:
    - name: dummy
      port: 12345

---
kind: StatefulSet
apiVersion: apps/v1
metadata:
  name: csi-yoda-provisioner
  namespace: kube-system
spec:
  selector:
    matchLabels:
      app: csi-yoda-provisioner
  serviceName: "csi-yoda-provisioner"
  replicas: 1
  template:
    metadata:
      labels:
        app: csi-yoda-provisioner
    spec:
      tolerations:
      - operator: Exists
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 1
            preference:
              matchExpressions:
              - key: node-role.kubernetes.io/master
                operator: Exists
      priorityClassName: system-node-critical
      serviceAccount: admin
      containers:
        - name: csi-provisioner
          image: registry.cn-hangzhou.aliyuncs.com/plugins/csi-provisioner:v1.5.4478651db-aliyun
          args:
            - "--provisioner=yodaplugin.csi.alibabacloud.com"
            - "--csi-address=$(ADDRESS)"
            - "--volume-name-prefix=yoda"
            - "--feature-gates=Topology=True"
            - "--v=5"
          env:
            - name: ADDRESS
              value: /var/lib/kubelet/plugins/yodaplugin.csi.alibabacloud.com/csi.sock
          imagePullPolicy: "IfNotPresent"
          volumeMounts:
            - name: socket-dir
              mountPath: /var/lib/kubelet/plugins/yodaplugin.csi.alibabacloud.com
      volumes:
        - name: socket-dir
          hostPath:
            path: /var/lib/kubelet/plugins/yodaplugin.csi.alibabacloud.com
            type: DirectoryOrCreate
  updateStrategy:
    type: RollingUpdate
